# Permalinks
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               DSincerity's blog
tagline:             'Tech & Life'
description:         Kwon Deuk Sin<br>Problem Solver with Data<br>Data Scientist/ML Engineer
url:                 https://DSincerity.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              KWON DEUK SIN
  #url:               https://hoisharka.github.com
  email:             kds0281@gmail.com
  gravatar:          aa88f7c64c7cbc6c3e3381367c14cfe2
  contact:
    linkedin:  https://www.linkedin.com/in/deuk-sin-kwon-268179153/
    #github:  https://github.com/DSincerity
    #facebook:  
    #twitter:  <hide>
    #weibo:    <hide>
    email:    mailto:kds0281@gmail.com
    
# Custom vars
version:             1.0.0

plugins: [jekyll-paginate]

# Tag setting
#collections:
#  tags:
#    output: true
#    permalink: /tags/:path/

#defaults:
#  - scope:
#      path: ''
#      type: tags
#    values:
#      layout: tag

google_analytics:
  ua: 'UA-109898110-1'

github:
  repo: 'https://github.com/hoisharka/hoisharka.github.io'

category_dir: category/
tag_dir: tag/
excerpt_separator: ""
disqus_short_name: dsincerity